### PR TITLE
LPS-90872 portal-search-admin-web: Make index information optional.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ccohick** [comment]
ci:test:bundle:norebase

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71482. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/c3dc497edb4e~4...c3dc497edb4e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
