### PR TITLE
LPS-67326 - Calendar button-holder in Asset Publisher add dialog shouldn't be in middle of layout

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @pat270

### CODE REVIEW

**Comment by vicnate5** [comment]
Hey @brandizzi Do you still have plans to add this to master?

**Comment by marcellustavares** [comment]
@brandizzi, could you please review this pull request?

Thanks

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/734. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
