### PR TITLE
LPS-90872 portal-search-admin-web: Build Language

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ccohick** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/669. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/aebcb8634a1d~1...aebcb8634a1d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
