### PR TITLE
LPS-85384 and LPS-85386 Added test to DDMFormInstasce, DDMFormInstanceRecord, DDLRecord and DDLRecordSet

### PR DESCRIPTION
**Pull request by vagnerbc**

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/640. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
