### PR TITLE
LPS-94257 Create OrganizationMultiLanguageSearchTest

### PR DESCRIPTION
**Pull request by vagnerbc**
https://issues.liferay.com/browse/LPS-94258

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/694. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
