### PR TITLE
LPS-65822 updating other calendars key on upgrade

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hey @linolaoj!

Thanks, great job!

I'm a bit surprised it was open yet, I thought we worked on it a long time ago! Indeed, we have some old pull requests with it: https://github.com/brianchandotcom/liferay-portal/pull/40557

That brings me some questions BTW. I believe this upgrade process could be better in the `calendar-web` module, since `calendar-service` does not depend on it and it is mostly a front-end thing.

Also, a note: you added it to the upgrade to the `3.0.0` build version. If we do it, this fix will only be released in Liferay 7.1. If we want to backport it, it should be an upgrade process between `1.0.0` and `2.0.0` (not including limits). I guess it will not be a problem on `calendar-web` though, where there are no such major bumps AFAIK.

Could you check these points? Feel free to reuse the [old pull request](https://github.com/brianchandotcom/liferay-portal/pull/40557) by the way, because it has some tests as well.

Any questions, let me know.

Thanks!

**Comment by linolaoj** [comment]
Hi @brandizzi , I rebased the old pull here https://github.com/brandizzi/liferay-portal/pull/506
Thanks!

**Pull request closed without merging**
