### PR TITLE
LPS-52482 Simplify

### PR DESCRIPTION
**Pull request by mdelapenya**
Do you agree with these changes? Thanks\!

### CODE REVIEW

**Comment by brandizzi** [comment]
Well, it would not work if the .orig file exists. My tomcat-users.xml keeps changing (and I don't know why so far, since I always set up the tomcat after a Liferay rebuild) and I have not noted if the .orig files exists after that. If you prefer this one, we can merge it and I can report any other problems.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello @mdelapenya!

It happened right now: the `tomcat-users.xml` file was reverted for some reason other than a portal rebuild. Sadly, `tomcat-users.xml.orig` is still present there.

If you merge your simplified solution, it would be less useful to me: I'd have to remove the file manually before running the task. It would be best than removing the whole manager directory, however. If it is the only way to get it merged into master, I'd go by it.

Yet, don't you think checking the value of the properties better? I've found at least two ways of doing it:
* import `tomcat-users.xml` as a property file: https://github.com/brandizzi/liferay-portal/commit/LPS-52482-FAVORITE-PREFIX
* use xmltask (which I discovered is still available in `liferay-portal`): https://github.com/brandizzi/liferay-portal/commit/LPS-52482-XMLTASK

Of course, it is up to you to decide which approach is better (after all, you all maintain it). Nonetheless, checking some other fact when we can check the configuration may be a more reliable approach, although maybe a bit longer to write.

What do you think?

**Comment by mdelapenya** [comment]
Hey Adam, if you think is better the XML check, I'm on that party too :)

Please remove my commit and sent your fix to Shuyang or Brian

Byes!

**Comment by brandizzi** [comment]
Forwarded to https://github.com/shuyangzhou/liferay-portal/pull/1079.

**Pull request closed without merging**
