### PR TITLE
LPS-86729 journal-test: Add integration test to check the indexed fields and reindexing for JournalArticle.

### PR DESCRIPTION
**Pull request by leomiyagi**

### CODE REVIEW

**Comment by leomiyagi** [comment]
ci:test:search:norebase

**Comment by leomiyagi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/805. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75672. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
