### PR TITLE
[TECHNICAL SUPPORT] LPS-76559

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-76559

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53748. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/ee60e82d0bc2~1...ee60e82d0bc2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Thanks, @jorgediaz-lr, perfect fix!

**Pull request closed without merging**
