### PR TITLE
LPS-101102 portal-search-tuning-rankings-web: Update css classnames for consistency

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
closing due to conflicts.

**Comment by brandizzi** [comment]
reopening as a reminder

**Comment by thektan** [comment]
Hey @brandizzi, I'll take a look at these conflicts and send you a new PR.

**Comment by thektan** [comment]
New PR: https://github.com/brandizzi/liferay-portal/pull/869

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
See #869 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
