### PR TITLE
LPS-75289 SF

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:reopen

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52427. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/5692d44~1...5692d44) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
