### PR TITLE
LPS-94371 Create multi language tests to bookmarksFolder and bookmarksEntry

### PR DESCRIPTION
**Pull request by vagnerbc**
https://issues.liferay.com/browse/LPS-94371

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/foshiro/liferay-portal/pull/3. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
