### PR TITLE
LPS-94506 blogs-test: Create BlogsEntryMultiLanguageSearchTest

### PR DESCRIPTION
**Pull request by foshiro**
PR reviewed: https://github.com/foshiro/liferay-portal/pull/7

### CODE REVIEW

**Comment by foshiro** [comment]
ci:test:sf:norebase

**Comment by foshiro** [comment]
ci:test:search:norebase

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/796. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
