### PR TITLE
LPS-70217

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brandizzi,

Attached is an update for http://issues.liferay.com/browse/LPS-70217.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46634. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
