### PR TITLE
Functional test fixes + fixup! LPS-101102 portal-search-tuning-rankings-web: Display duplicate aliases in error message

### PR DESCRIPTION
**Pull request by joshchong**
@brandizzi @thektan I added the functional test fixes here and I'll rerun the search tests. If things pass it should be good to push up if nothing else is needed on your end.

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
@brandizzi the ci:test:search results looks good!

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82290. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
