### PR TITLE
LPS-94548 Create UserGroupMultiLanguageSearchTest

### PR DESCRIPTION
**Pull request by leomiyagi**
leomiyagi#10

### CODE REVIEW

**Comment by leomiyagi** [comment]
ci:test:search:norebase

**Comment by leomiyagi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75054. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/784. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
