### PR TITLE
LPS-58159 Regenerate Calendar

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:retest

**Comment by vicnate5** [comment]
@inacionery @brandizzi Got a console error when I added Calendar to a page with this pull :/
https://gist.github.com/vicnate5/80aae8003ecf9690a384

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/821. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/f5186b5~4...f5186b5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
