### PR TITLE
LPS-55026 Minor SF

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@shuyangzhou @mtambara

**Comment by brandizzi** [comment]
@michaelhashimoto is this pull request causing a problem?

**Comment by michaelhashimoto** [comment]
@brandizzi - no we had to reset the jenkins servers, but these tests will likely fail due to changes in master.  @shuyangzhou wanted to see those results so he can fix them.  This was just the first PR to run after my fix for the jenkins servers went in.. sorry for the inconveniences

**Comment by shuyangzhou** [comment]
@michaelhashimoto the build finished, how come the report is not back?

@brianchandotcom this does not look good. There are massive failures, I can not even count them.

**Comment by shuyangzhou** [comment]
@michaelhashimoto this is not right. Go into the backend build link, you can see there are tons of failures. But only the sf one is reported. And how is it still taking so long to get back the report? The build has finished for a very long time.

**Comment by michaelhashimoto** [comment]
There should be results here:
https://test-1-7.liferay.com/job/test-portal-acceptance-upstream-backend(master)/59/

**Comment by shuyangzhou** [comment]
Yeah, I know where to find the results. But they are not properly reported back. Other developers won't know where to find them.

**Pull request closed without merging**
