### PR TITLE
[TECHNICAL-SUPPORT] LPS-50892 As a calendar resource user, I should not be able to overlap/double book events on a resource

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @brandizzi 

I'm resending https://github.com/brandizzi/liferay-portal/pull/399 because of failed tests.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by brandizzi** [comment]
Hey István!

There is a baseline error, I'll try to solve it myself. Tomorrow I'll work on it.

Thank you for yet another fix :tada:

**Comment by brandizzi** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Hey @brandizzi 

Sorry, you don't have to reopen it. I have sent the same fix with the corrected baseline.
You can ignore this pull.

**Pull request closed without merging**
