### PR TITLE
LPS-92859 portal-search-elasticsearch6-impl: Implement support to Spanish synonyms.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Hey Adam, @brandizzi 

This feature will be supported when running the portal with Elasticsearch, right?

**Comment by brandizzi** [comment]
Hey @lipusz! Yes, that's true.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/735. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/9f2cf54cbfcb~3...9f2cf54cbfcb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
