### PR TITLE
LPS-65972 Use jabsorb serializer due incompatibility with newest Liferay's JSON serializer

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @vicnate5

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40076. Thank you! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
