### PR TITLE
LPS-101102 - Result Rankings: Adding a duplicate alias removes all unsaved changes

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-101102

Fixed the rebase issues.

It seems like the only relevant failure is for the test [`LocalFile.SearchTuning#AssertCannotAddDuplicateQueriesAndAliases`](https://testray.liferay.com/reports/production/logs/test-1-10/1574706978085/test-portal-acceptance-pullrequest(master)/2465/functional-tomcat90-mysql57-jdk8/12/0/LocalFile.SearchTuning_AssertCannotAddDuplicateQueriesAndAliases/summary.html.gz), which simply needs a text update. It's currently looking for 'A ranking already exists' when it should be 'A ranking with that search query already exists' @joshchong

https://github.com/brandizzi/liferay-portal/pull/879#issuecomment-557762954

### CODE REVIEW

**Comment by joshchong** [comment]
I can take a look

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thektan** [comment]
@brandizzi @joshchong Updated!

- Fixed the back and cancel buttons after an error on the "New Ranking" page.
- Unexpected errors on the "New Ranking" page will now appear on top as a dismissable alert like how the duplicate search query error appears.
- Updated the error.jsp to show the generic "unexpected error" alert.
- Removed unused language keys and ran `gradlew buildLang`

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/895. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/3ba94907fc4e~2...3ba94907fc4e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Thank you so much, @thektan!

**Pull request closed without merging**
