### PR TITLE
[TS] LPS-89093 Activate component immediately in order to avoid waiting if index.on.startup is enabled.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Based on https://github.com/liferay/liferay-portal-ee/pull/12409

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hello Mariano,

Please add the [TS] designation to the subject.

Thank you!

**Comment by brandizzi** [comment]
ci:test:relevant:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello, @marianoalvarosaiz!I started looking at it but did not finish yet. Sadly, I'll be out of office tomorrow so I may only get back to it by Friday. I have some questions but... well, better see everything before asking, I guess :)

Thank you for the pull request! I will try to get a feedback on it this week still.

**Comment by brandizzi** [comment]
ci:test:stop

**Comment by brandizzi** [comment]
ci:stop

**Comment by marianoalvarosaiz** [comment]
Thanks @brandizzi. No worries, it can wait.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:stop

**Comment by brandizzi** [comment]
Hey @marianoalvarosaiz! This is a great pull request, I am learning quite a bit here :) I have some questions that I want to clarify, but I want to study it a bit more before getting to them. Meanwhile, just a question: I saw there is an `AssetRendererFactoryLookup` in portal-search-web. Do you know where it came from? Maybe we could put the impl there too? 

Also, what about putting this lookup and its impli inside `asset-service`/`asset-api`? I'm mostly spitballing here, but what do you think?

Also, what is the behavior this change is fixing? Would it be too difficult to create a ticket just for this behavior? (Here I suppose it is something like unindexed content or some exception; if the only bad behavior is the delay not honored, then this ticket is perfect.)

Meanwhile, I have two little requests: could you rename `_assetRenderFactoriesCountDownLatch` to `_assetRenderFactoriesCountDownLatchMap`? Also, I don't see clearly what `_isEnabled()` means only by its name; would you have some other idea about how to name it?

I'm sorry for so many questions, it's that this fix is quite significant. Let's work together, I'll be waiting for your comments.

And again thank you so much!

**Comment by marianoalvarosaiz** [comment]
Hi @brandizzi, thanks a lot for your reply. Trying to answer your questions:


 > Meanwhile, just a question: I saw there is an AssetRendererFactoryLookup in portal-search-web. Do you know where it came from? Maybe we could put the impl there too?

It was added in https://github.com/brianchandotcom/liferay-portal/pull/48503/files just to be able to test SearchResultSummaryDisplayBuilder

---

> Also, what about putting this lookup and its impli inside asset-service/asset-api? I'm mostly spitballing here, but what do you think?

Makes sense to me.

---

> Also, what is the behavior this change is fixing? Would it be too difficult to create a ticket just for this behavior? (Here I suppose it is something like unindexed content or some exception; if the only bad behavior is the delay not honored, then this ticket is perfect.)

It's trying to solve the fact that delay isn't honoured, and that implies that when indexing on startup there can be a race condition causing asset fields not added to a certain type of document if that type of document's AssetRendererFactory hasn't been tracked yet by the AssetRendererFactoryRegistryUtil ServiceTracker.

---

> Meanwhile, I have two little requests: could you rename _assetRenderFactoriesCountDownLatch to _assetRenderFactoriesCountDownLatchMap? Also, I don't see clearly what _isEnabled() means only by its name; would you have some other idea about how to name it?

For sure, I'm awful with names. What do you think about _isEnabled -> _isIndexOnStartupEnabled?

As soon as we "close" all these facts I can send you a new PR with all the changes.

Kind regards.

**Comment by lipusz** [comment]
ci:test:relevant:9d9fde2b59f8d50feed7ccd01519dbd8edf064a9

**Comment by lipusz** [comment]
ci:test:search:9d9fde2b59f8d50feed7ccd01519dbd8edf064a9

**Comment by brandizzi** [comment]
Hey @marianoalvarosaiz! I'm closing this PR while we wait for your updates. Let me know if you need anything. Thanks!

**Comment by marianoalvarosaiz** [comment]
see https://github.com/brandizzi/liferay-portal/pull/966

**Pull request closed without merging**
