### PR TITLE
LPS-90068 Fix package name and class name

### PR DESCRIPTION
**Pull request by foshiro**
Task: https://issues.liferay.com/browse/LPS-90068

### CODE REVIEW

**Comment by foshiro** [comment]
ci:test:sf

**Comment by foshiro** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68426. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/629. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/3e933b6963eb~2...3e933b6963eb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
