### PR TITLE
LPS-103224 Fix SearchHitDocumentTranslator to handle FieldArray

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:search

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:search

Previous test failed for unrelated network issue:
`ssh: Could not resolve hostname github.com: Name or service not known`

**Comment by brandizzi** [comment]
Hey @knchau, @inacionery! I'm deliberating with the team about what to do here. See our [Slack thread](https://liferay.slack.com/archives/CKY6F59A6/p1571860550021400). I believe I cannot accept it myself so let's see what happens. Sorry for the delay, let's try to finish it at once.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
ci:test:relevant:5ac6ae19ca00eb455194dd26991db70ba58363cd

**Comment by lipusz** [comment]
ci:test:search:5ac6ae19ca00eb455194dd26991db70ba58363cd

**Comment by lipusz** [comment]
Testing on latest stable search hash (https://search-ci.liferay.com/)

**Comment by knchau** [comment]
Hi @inacionery,

Will you be updating this PR in relation to Bryan's [tests](https://github.com/natocesarrego/liferay-portal/pull/195)?

Thank you!

**Comment by inacionery** [comment]
Hey @knchau,

Could you please talk to @natocesarrego, he's responsible for it now. I was just helping the DDM team, but I'm now with other priorities.

Thanks!

**Comment by natocesarrego** [comment]
Hi @knchau,

@inacionery told me about Bryan's pull, however I wasn't able to review it yet for 2 reasons:

- The pull will demand a considerable amount of time to review, once it has a lot of commits.
- My current bandwidth is filled by other high priority requests.

As soon as possible, I'll review the mentioned pull.

Thanks for your understanding.

**Pull request closed without merging**
