### PR TITLE
LPS-92499 portal-search-ranking-web: UI: Synonyms form

### PR DESCRIPTION
**Pull request by foshiro**
Task: https://issues.liferay.com/browse/LPS-92949

### CODE REVIEW

**Comment by ccohick** [comment]
ci:test:bundle

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ccohick** [comment]
when running off the bundle in the chat above, I don't show the empty state animation of the main screen, like in the Custom Rankings UI. Would we be able to add it to the Synonyms screen as well for consistency?

**Comment by foshiro** [comment]
Hi @ccohick, the synonym sets list and the empty state animation will be added on task https://issues.liferay.com/browse/LPS-92949, with PR https://github.com/brandizzi/liferay-portal/pull/678

**Comment by ccohick** [comment]
thanks so much!

**Comment by brandizzi** [comment]
merged into brandizzi#synonyms <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
