### PR TITLE
LPS-52423

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
@brandizzi 

do you have time to review this ticket ?

thanks in advance.

David.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by hhuijser** [comment]
Hey @brandizzi 

This one still on your radar?
Is this even still a bug?

Can you either review or close the pull?

**Comment by brandizzi** [comment]
Sorry @daviddotzhang and @hhuijser, it just fell out of my attention. Let me take care of that now.

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/448. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/c39017f~2...c39017f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
