### PR TITLE
LPS-69192 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
@brandizzi, since you're the class owner, could you please review this pull? Also, could you please expand our tests to cover this bug?

Thanks for the fix @sherlyliu!

Thanks

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey @brandizzi 
Could you help to review this pull request? it is for ee customer.

**Comment by marcellustavares** [comment]
@daledotshan, tests for the bug are missing. This is not only a review, it will take more time.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
@daledotshan @sherlyliu Thanks for the fix! I believe I've found a security problem on it and I'm investigating. If everything goes as expected, I'll just need to complement your fix a bit (and also write some tests.) I'll keep you all informed.

Thanks!

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1714. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/4d23157~3...4d23157) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
