### PR TITLE
LPS-94561 Alphabetical sorting multi language

### PR DESCRIPTION
**Pull request by foshiro**
PR reviewed: https://github.com/foshiro/liferay-portal/pull/5
Alpha tested. 
Followed steps to reproduce from task: https://issues.liferay.com/browse/LPS-93341
order_by_title

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase

**Comment by brandizzi** [comment]
ci:test

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/787. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
