### PR TITLE
LPS-67704

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brandizzi 
This one is customer related and quite urgent.

**Comment by daledotshan** [comment]
Hey Brand,
Could you help to review this pull request as a high priority? it is a little bit of urgent, it is for a ee customer

Thanks,
Dale

**Comment by brandizzi** [comment]
I'll have to do it Monday but will be my highest priority.

Thanks for your attention and patience!

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1588. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/ef1c67b~2...ef1c67b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
