### PR TITLE
[TS] LPS-89093 Fix index.on.startup

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by brandizzi** [comment]
Thank you! I have another PR on the queue (and a lot of people needing help
:sweat_smile:  ) but I will at least take a look today in the airport ;)

**Comment by brandizzi** [comment]
@marianoalvarosaiz Sorry, just saw now you've closed it. I should wait for a new one then?

**Comment by marianoalvarosaiz** [comment]
Sorry @brandizzi,
 Tibor recommended me to create the pull over the latest stable hash.
Kind regards.

**Pull request closed without merging**
