### PR TITLE
LPS-97813 Tests (Indexed fields, reindex and multilanguage) to DDLRecord, DDLRecordSet, DDMFormInstance and DDMFormInstanceRecord

### PR DESCRIPTION
**Pull request by vagnerbc**
https://issues.liferay.com/browse/LPS-97813
https://issues.liferay.com/browse/LPS-97809

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/802. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/034c0b04fa34~2...034c0b04fa34) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
