### PR TITLE
LPS-69566 Fix recurringCalendarBookingId when isMasterRecurringBooking

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47299. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/fe21635~4...fe21635) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
