### PR TITLE
LPS-85852 New Indexers: AssetVocabulary & AssetVocabulary & AssetTag

### PR DESCRIPTION
**Pull request by ifnazar**

### CODE REVIEW

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
@brandizzi : used code of branch https://github.com/brandizzi/liferay-portal/commits/pr-583

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/610. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
