### PR TITLE
LPS-85855

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69205

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
- [ ] reorder

		setUpUserSearchFixture();
		setUpTrashEntryFixture();
		setUpTrashEntryIndexerFixture();
		setUpIndexedFieldsFixture();

    Can you sort these, or add a line break if setUpIndexedFieldsFixture has to come last.

     Type: git grep setUpIndexedFieldsFixture

     Fix in all those classes too. Thx.

- [ ] TrashKeywordQueryContributor is in the wrong package (please fix else where) for  *KeywordQueryContributor

    Should be in

    internal.search.spi.model.query.contributor to match com.liferay.portal.search.spi.model.query.contributor

- [ ] Apply 67db3f7 else where

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/636. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/12db7bbf85f7~2...12db7bbf85f7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/638. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/e9f754544824~2...e9f754544824) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
