### PR TITLE
LPS-86734 portal-search: remove resourcedModel validation.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:relevant:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jorgediaz-lr** [comment]
Hi @brandizzi @luanmaoski 

I saw this PR by chance.

About the BufferedIndexerInvocationHandler code that is removed in https://github.com/brandizzi/liferay-portal/pull/808/commits/9f7cba0190d727f88a227af6d279a91129ef6f0c please, don't remove it as it was added in order to avoid https://issues.liferay.com/browse/LPS-67703 (_When creating or updating a ResourcedModel, IndexerRequestBuffer stores and executes two index requests_)

With that code, we avoid multiple reindex operation in JournalArticle as we only add to index buffer one request with the **resourcePrimKey**.

If we remove that code, we will have one reindex operation using **resourcePrimKey** and several other reindex operations using JournalArticle primary key: **id_**

That is very problematic in case of Export/Import or Staging, because several JournalArticle versions are published and for example, in case you have 5 versions, you will end having 6 reindex operations, but only 1 is necessary.

So please, don't remove that logic, or in case you want to remove it, please, test https://issues.liferay.com/browse/LPS-67703 issue, as I think it will be reproduced again after removing that code.

Next week I will be out of office, so in case you have any question, I won't be avaliable until 22/07/2019. 

Thank you,
Jorge

**Comment by brandizzi** [comment]
Hey @jorgediaz-lr! Don't worry, I had no intention of merging this pull request so far! I've got this proposed fix and found it really strange. That's why I've submitted it and run various test suites on it. 

While I'm sorry I scared you guys :sweat_smile: I'm also glad to get your feedback. Thank you!

cc @leomiyagi @luanmaoski

**Comment by luanmaoski** [comment]
Hi @jorgediaz-lr , i posted a commentary about this problem here: [LPS-86734](https://issues.liferay.com/browse/LPS-86734)

cc @leomiyagi

**Pull request closed without merging**
