### PR TITLE
LPS 62735

### PR DESCRIPTION
**Pull request by mbowerman**
Hey Adam,

I haven't tested this super-thoroughly, but I wanted to get something to you to see if it's closer to what you're looking for. There are still some minor things that haven't been done such as fixing the bug in RecurrenceSerializer

The biggest problem right now is that it doesn't recognize an event as recurring if you update "only this instance" and select the updated instance. This in itself should be easy to fix (add calendarBookingId != recurringCalendarBookingId as a condition for isRecurring()); however, once the user is allowed to interact with these instances as recurring events, we will need to severely modify the logic for updateCalendarBookingInstance and deleteCalendarBookingInstance. I wanted to get this pull request to you sooner rather than later, so I did not fix this issue before submitting the pull request.

Please let me know if this pull request is more along the lines of what you're looking for.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Worked on it. NOw working with https://github.com/brandizzi/liferay-portal/pull/232 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
