### PR TITLE
LPS-89093 Add logic to verify and apply the portal startup delay

### PR DESCRIPTION
**Pull request by leomiyagi**
https://issues.liferay.com/browse/LPS-89093

----------------------------
Class IndexOnStartupIndexerServiceCustomizer.addingService
- All indexers have the propertie "index.on.startup = true" by default;
- Creates the IndexOnStartupPortalInstanceLifecycleListener for each indexer and registers it in serviceRegistration;

----------------------------
Class IndexOnStartupPortalInstanceLifecycleListener.portalInstanceRegistered
- For all indexers do not enter the _indexWriterHelper.reindex method if the propertie is false;
- Stack:
1.     IndexWriterHelperImpl
2.     ReindexSingleIndexerBackgroundTaskExecutor
3.     Class Indexer of respective indexer

---------------------------

A logic was implemented to wait for a set time in the "index.on.startup.delay" property before reindexing the registry.

**Setting a delay does not really solve the problems.
Most records are reindexed, but not all.
At each startup a different amount of records are reindexed.
Still have the intermittent problem that some records are not reindexed.**

### CODE REVIEW

**Comment by leomiyagi** [comment]
ci:test:search

**Comment by leomiyagi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/818. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/861ba639b098~1...861ba639b098) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
