### PR TITLE
[TECHNICAL-SUPPORT] LPS-50892 As a calendar resource user, I should not be able to overlap/double book events on a resource

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @brandizzi

I'm resending https://github.com/brandizzi/liferay-portal/pull/401 because of failed tests.

Best regards,
István

### CODE REVIEW

**Comment by brandizzi** [comment]
Hey István!

Tomorrow I'll work on it.

Thank you for yet another fix :tada:

**Comment by IstvanD** [comment]
Hey Adam!

This is the same fix as https://github.com/brandizzi/liferay-portal/pull/401, but in this pull, the baseline is correct.

You can ignore https://github.com/brandizzi/liferay-portal/pull/401 and only focus on this one.

Thank you!

Bests,
István

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/410. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/a977b5d~8...a977b5d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/411. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/541b67c~17...541b67c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49463. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/311d357~17...311d357) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
