### PR TITLE
LPS-71251

### PR DESCRIPTION
**Pull request by eperezg**
cc/ @natocesarrego

### CODE REVIEW

**Comment by eperezg** [comment]
hi @brandizzi 

Could you take a look at this pull?

regards.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47777. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/c4d0435~1...c4d0435) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hy @eperezg!

Sure, my bad. Reviewed and forwarded.

Just a note, I did a little change [here](https://github.com/brianchandotcom/liferay-portal/pull/47777/commits/c4d0435ca0c142b5e3401efe2236cfefdee000af) because other services (such as [DLFileEntryServiceImpl](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFileEntryServiceImpl.java#L199-L210) and [JournalArticleServiceImpl](https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleServiceImpl.java#L412-L424)) throw the exception and I'm afraid of diverging from them ;)

Thanks, this fix really helped us!

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47789. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/3af2d90~1...3af2d90) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
