### PR TITLE
LPS-66844 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

@brandizzi Please forward to @vicnate5 when you finish. 

@vicnate5 We need to change the way we use the value for a select field using a data provider. Inspect the HTML and you'll see. Please let me know if you need more explanation.

**Comment by leoadb** [comment]
ci:reopen

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46177. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/41340f3~1...41340f3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/709. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/aa38f6d~1...aa38f6d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
