### PR TITLE
LPS-89060 New Indexer: Layout

### PR DESCRIPTION
**Pull request by ifnazar**
@vagnerbc

### CODE REVIEW

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:relevant

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/607. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
