### PR TITLE
LPS-72940 Add MailTestRule to CalendarUtilTest

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/427. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/c2f7240~3...c2f7240) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49919. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/5059240~3...5059240) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
