### PR TITLE
LPS-55534

### PR DESCRIPTION
**Pull request by samuelkong**
/cc @neilking

### CODE REVIEW

**Comment by samuelkong** [comment]
bump

**Comment by neilking** [comment]
This is still in review?

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
cc @samuelkong <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/neilking/liferay-portal/pull/68. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/f4e842e~2...f4e842e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/285. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/4874a0b~3...4874a0b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
