### PR TITLE
LPS-74781 Use constant instead of string to refer to the Asset Browser Portlet.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51890. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/64f8194a~3...64f8194a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51917. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/04ce15a~3...04ce15a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
