### PR TITLE
LPS-70524 Wrong date format in Calendar day view

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:stop

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey Adam,

I was wondering if you could find time to review this pull.
Please don't hesitate to ask if you have any questions regarding it.

Thank you.

Best regards,
István

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47242. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/7c9b6fc~3...7c9b6fc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/752. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/2e6cf47~3...2e6cf47) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
