### PR TITLE
[Technical-Support] LPS-59573

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Adam,

The issue came from EE customer. Is it possible that you can review this with a higher priority?

Best Regards,
Hai

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello @yuhai, @hhuijser.

I found this behavior rather strange: there should never be a situation where the calendar id to be removed is not found on that array. After some research, I tracked it to a wrong default calendar id. A different fix is with @brunobasto right now: https://github.com/brunobasto/liferay-portal/pull/286

Thank you again!

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
