### PR TITLE
[TECHNICAL-SUPPORT] LPS-61835

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ericyanLr

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello Eric!

The tests on my machine were still reproducing the bug. This is the value of `/etc/apache2/sites-enabled/000-default.conf` on my machine:

    <VirtualHost *:80>
            # The ServerName directive sets the request scheme, hostname and port that
            # the server uses to identify itself. This is used when creating
            # redirection URLs. In the context of virtual hosts, the ServerName
            # specifies what hostname must appear in the request's Host: header to
            # match this virtual host. For the default virtual host (this file) this
            # value is not decisive as it is used as a last resort host regardless.
            # However, you must set it for any further virtual host explicitly.
            #ServerName www.example.com
    
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html
    
            # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
            # error, crit, alert, emerg.
            # It is also possible to configure the loglevel for particular
            # modules, e.g.
            #LogLevel info ssl:warn
    
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
    
            # For most configuration files from conf-available/, which are
            # enabled or disabled at a global level, it is possible to
            # include a line for only one particular virtual host. For example the
            # following line enables the CGI configuration for this host only
            # after it has been globally disabled with "a2disconf".
            #Include conf-available/serve-cgi-bin.conf
    
            ProxyPass / ajp://192.168.108.217:8009/
            ProxyPassReverse / ajp://192.168.108.217:8009/
    
    </VirtualHost>
    
    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet

At `/etc/hosts` I added the line

    192.168.108.217 test.com

I also configured the instance in the portal:

instance-domain

Everything worked well, I could access Liferay from test.com. Yet, I still got emails with the 8080 port.

After some debugging, I've noticed the port and the host come from the `PortalImpl._portalLocalInetSocketAddress` attribute. It is set at the first request, apparently. On my machine, it appears the portal itself makes a request to `localhost:8080`, which forces it to be the URL used by `PortalUtil`.

If I 
* put a breakpoint at `PortalImpl:6882` before starting the portal;
* start the portal;
* let the breakpoint paused to avoid having `_portalLocalInetSocketAddress` set to `localhost`;
* make a request to `test.com`; 
* make the new resulting thread continue; and then
* make the original thread continue

then the fix works.

Have you seen something like it? Do you think it would be feasible to check this problem?

Thanks! Let me know of any doubts, I'm sure my explanation may be a bit contrived...

cc @ericyanLr

**Comment by ericyanLr** [comment]
Hey @brandizzi,

Thanks for providing your detailed configuration and debugging process for testing this fix.
Everything looks good on the configuration you provided.

There are two things that may be missing on your setup:
- portal-ext.properties
```
# This allows us to use test.com and localhost:80
web.server.host=test.com
web.server.http.port=80
web.server.https.port=443
```
- [LPS-4959](https://issues.liferay.com/browse/LPS-4959)
    * This fixes the port issue in general
        * Reference: [5096e2a9cf...bfccd02a10](https://github.com/brianchandotcom/liferay-portal/compare/5096e2a9cf...bfccd02a10)
    * This commit was submitted for the same LPP ticket on 1/7/2016 and is needed for this fix to work.

Apologies, the steps in the LPS ticket were a bit unclear. I will add these two points on the ticket for future reference.

Please let me know if you have any other questions.
Thanks!

**Comment by brandizzi** [comment]
Hey @ericyanLr! Thanks for your answer.

The properties were already set at portal-ext.properties (excepti for `web.server.host`). I just forgot to mention them. My bad! These are the properties at my file:

    web.server.host=test.com
        web.server.http.port=80
            web.server.https.port=443



Also, LPS-4959 is already merged.

Yet, even with these changes, the URL keeps being generated with the port. For example, this is one of the emails I've got:
                                                                                                                                                                                                                                                                  
    Return-Path: <liferay.for.testing@gmail.com>
    Received: from zizek ([187.103.79.116])
            by smtp.gmail.com with ESMTPSA id c2sm56798655qkb.41.2016.01.12.06.26.36
            for <liferay.for.testing+1@gmail.com>
            (version=TLSv1/SSLv3 cipher=OTHER);
            Tue, 12 Jan 2016 06:26:37 -0800 (PST)
    Date: Tue, 12 Jan 2016 14:26:32 +0000 (GMT)
    From: Joe Bloggs <liferay.for.testing@gmail.com>
    To: liferay.for.testing+1@gmail.com
    Message-ID: <719440317.01452608797250.JavaMail.adam@zizek>
    Subject: Calendar: Event Notification for "tiredd"
    MIME-Version: 1.0
    Content-Type: text/html;charset="UTF-8"
    Content-Transfer-Encoding: 7bit
    X-Auto-Response-Suppress: AutoReply, DR, NDR, NRN, OOF, RN
    
    user 1,<br /><br />
    
    You have been invited to event <a href="http://test.com:8080/c/portal/layout?p_l_id=20232&p_v_l_s_g_id=0&_com_liferay_calendar_web_portlet_CalendarPortlet_mvcPath=%2Fview_calendar_booking.jsp&p_p_id=com_liferay_calendar_web_portlet_CalendarPortlet&p_p_lifecycle=0&p_p_state=maximized&_com_liferay_calendar_web_portlet_CalendarPortlet_calendarBookingId=22005">tiredd</a> that will start on <strong>1/12/16 3:00 PM UTC</strong>.<br /><br />
    
    Sincerely,<br />
    Joe Bloggs<br />
    liferay.for.testing@gmail.com<br />
    http://test.com:8080

Even if I apply the breakpoint trick, I got the port 80 in the URL!

                                                                                                                                                                                                                                                                   
    Return-Path: <liferay.for.testing@gmail.com>
    Received: from zizek ([187.103.79.116])
            by smtp.gmail.com with ESMTPSA id p17sm56625659qhb.34.2016.01.12.10.35.06
            for <liferay.for.testing+1@gmail.com>
            (version=TLSv1/SSLv3 cipher=OTHER);
            Tue, 12 Jan 2016 10:35:07 -0800 (PST)
    Date: Tue, 12 Jan 2016 18:35:02 +0000 (GMT)
    From: Joe Bloggs <liferay.for.testing@gmail.com>
    To: liferay.for.testing+1@gmail.com
    Message-ID: <1463007642.01452623707067.JavaMail.adam@zizek>
    Subject: Calendar: Event Notification for "465465465"
    MIME-Version: 1.0
    Content-Type: text/html;charset="UTF-8"
    Content-Transfer-Encoding: 7bit
    X-Auto-Response-Suppress: AutoReply, DR, NDR, NRN, OOF, RN
    
    user 1,<br /><br />
    
    You have been invited to event <a href="http://test.com:80/c/portal/layout?p_l_id=20232&p_v_l_s_g_id=0&_com_liferay_calendar_web_portlet_CalendarPortlet_mvcPath=%2Fview_calendar_booking.jsp&p_p_id=com_liferay_calendar_web_portlet_CalendarPortlet&p_p_lifecycle=0&p_p_state=maximized&_com_liferay_calendar_web_portlet_CalendarPortlet_calendarBookingId=22305">465465465</a> that will start on <strong>1/12/16 6:40 PM UTC</strong>.<br /><br />
    
    Sincerely,<br />
    Joe Bloggs<br />
    liferay.for.testing@gmail.com<br />
    http://test.com:80

I have even set `browser.launcher.url` to http://test.com here (it was empty before) to no avail. Haven't you set other specific property at all?

After looking at other portlets sending emails, I noted a striking difference between them and the calendar. Note that the message boards notification is sent directly from the a request processing thread. It means that they have a a request with the original URL. We have no such information when sending a reminder.

I'm sorry, but I do not know what else to do here. The URL retrieving methods are too complex to me to understand and I do not see what can be wrong with my environment. Many people are having other issues with the calendar; I'll postpone this one a bit. Maybe I'll see something if give it some time. If you have any ideas, just let me know, as well.

Sorry for the delay, and thanks for the answers and patience.

**Comment by ericyanLr** [comment]
Hey @brandizzi ,

Maybe I missed something on this fix, I will do some more tests and see if I can get the same results as yours. I'll let you know if I find anything.

Thanks again for your time and detailed test results!

**Comment by ericyanLr** [comment]
Hey @brandizzi,

I have just retested in a clean environment and everything worked on my end.  
1. Deployed latest liferay-portal (master) instance
2. Cherry-picked the changes from this pull request
3. Used gradlew to deploy calendar-service
4. Setup environment using the steps for this ticket.

The only thing that I noticed that was different is my apache configuration:
```
<VirtualHost *:80>
        ServerAdmin webmaster@test.com
        ServerName test.com
        DocumentRoot "C:/Program Files/Apache Software Foundation/Apache2.2/htdocs"
        ProxyPass / ajp://192.168.21.133:8009/
        ProxyPassReverse / ajp://192.168.21.133:8009/
</VirtualHost>
```

After looking through our previous comments, I have a few more insights on a few of the scenarios:
- Breakpointing to avoid having _portalLocalInetSocketAddress set to localhost
    - This should be resolved by the property I forgot to mention in the beginning:
        - web.server.host=test.com
            - If this property is set, it will be used for the URL
- Even if I apply the breakpoint trick, I got the port 80 in the URL!
    - For this scenario it is likely that the current change referenced in the pull request is not in effect
        - Link: [file changes](https://github.com/brandizzi/liferay-portal/pull/134/files)
        - Can try re-deploying calendar-service

Please let me know if there's anything else I can do to help.
Thanks!

**Comment by brandizzi** [comment]
Hey @ericyanLr!

Don't worry, it sounds like a problem on my end. I'll investigate it further, I just have to make my queue go on a bit :-/ It is just I don't feel comfortable to advance without knowing what is going on here.

Anyway, thank you for your attention and hard work. I hope to merge your PR in the following days.

**Comment by AngeloJ** [comment]
@brandizzi When you get a chance can provide us with an update? Thanks

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1107. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hey @AngeloJ et al.

It is working perfectly. As I've suspected, it was likely a problem with my environment. Sorry for the delay, and thanks for the comprehension!

**Pull request closed without merging**
