### PR TITLE
LSP-85856 New Indexers: mail-reader: Account & Folder & Message

### PR DESCRIPTION
**Pull request by foshiro**
PR reviewed: https://github.com/foshiro/liferay-portal/pull/6

### CODE REVIEW

**Comment by foshiro** [comment]
ci:test:sf:norebase

**Comment by foshiro** [comment]
ci:test:search:norebase

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/795. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
