### PR TITLE
LPS-75845 | master

### PR DESCRIPTION
**Pull request by jpince**
see https://issues.liferay.com/browse/LPS-75845 for details

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
forgot to add the ignore import <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52974. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
