### PR TITLE
LPS-74684 Create an integration test

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:reopen

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/459. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/e7b92da~4...e7b92da) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51655. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/fc91443~6...fc91443) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
