### PR TITLE
LPS-62069 Moving a recurring event to another date results the first event be placed to the wrong week

### PR DESCRIPTION
**Pull request by IstvanD**
Hey Adam,

I made some further adjustments to LPS-62069 because in CalendarPortlet.getFirstCalendarBookingInstance() the end and start times were not set in order.
I also made the calculation of the start date of firstDayJCalendar timezone aware.

Could you please check it if this is OK, and if yes, forward it?

Thanks!

Best regards,
István

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hey István!

Thanks for your dedication, I guess this problem is taking too much time from you... I have to confess I'm a bit list here; do you have some few steps to reproduce the problems you've found? I can understand the first commit and it is perfect, but I don't know how to reproduce the problem the second commit fixes.

Thanks!

**Comment by IstvanD** [comment]
Hey Adam,

I'm sorry for answering you this late.
The issue the second commit fixes is that, when you select another timezone in your account settings, say, India Standard Time, and move a weekly recurring event backwards in time (moving left) the whole series will start one week later.

Cheers,
István

**Comment by brandizzi** [comment]
Thanks István!

I'm already reviewing it since Monday. I had to travel due to a personal issue but tomorrow i'll work remotely, so I should finish this one. I'm just a bit lost with the code (not much this PR, but all changes we've made) so it is taking a bit more of time.

Thanks!

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
Hey @IstvanD!

I apologize for the delay. I'm not even in the office these days and there is a huge amount of people looking for me. The issue here is also very hard. I'll be back to it. Soon. Probably tomorrow.

Thanks for the patience!

**Comment by brandizzi** [comment]
Hey @IstvanD!

Sorry for the delay. As I've said, I just didn't understand what was going on...

Anyway, I did it. The first part was spot-on. The second part looked overly complex, so I spend most of  the time in it. Luckily, I've found a problem on a line I added long time ago. With that, it was fixed. Some more lines could even be removed.

OTOH I am not reproduce the time zone problem after the fix. (It is a relief: I tried hard to isolate all time zone stuff related to recurrences into `RecurrenceUtil.inTimeZone()`). If you find it again, don't hesitate on contact me or work on it!

I've sent a pull request to you, https://github.com/IstvanD/liferay-portal/pull/21, with my changes, so you can test.

Also, I've created a ticket about the bad ordering of startTime/endTime in the method. Hope I did not make it dastardly confusing :-/

So, thank you, really, for your fix and patience. I hope everything will be better now.

**Pull request closed without merging**
