### PR TITLE
LPS-90872 portal-search-admin-web: New dependency due to 54350c4e86cbf3c88136578627d06d75c758d51c.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/670. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/d7bbae9bb2f9~1...d7bbae9bb2f9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
