### PR TITLE
[7.2 Stabilization] LPS-96883 Localization issues with the Sort search widget labels

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-96883

QA Notes
The fix adds new lang keys which needs to be translated first and then synced back to the branches, until the default English text will appear for some

Solution Notes
Existing Sort widget instances where the widget (portlet) configuration was already saved must be updated manually and set the right labels (TBA)

Cheers,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
Branch is based off of latest stable Search hash.

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/74606

**Pull request closed without merging**
