### PR TITLE
[Technical Support] LPS-66558

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
Hi @brandizzi,

Could you please review this fix for us? Please let me know if I need send this to somebody else.

/cc @gergelyszaz 

Thank you,
Zoltán

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:reopen

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello @ZoltanTakacs!

I am sending this pull request to @natocesarrego, who is in charge of calendar PRs now.

Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello @ZoltanTakacs!

I am sending this pull request to @natocesarrego, who is in charge of calendar PRs now.

Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request forwarded to https://github.com/natocesarrego/liferay-portal/pull/42. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ZoltanTakacs** [comment]
Thank you @brandizzi! I'll keep that in my mind. :)

**Pull request closed without merging**
