### PR TITLE
LPS-92858 Fix DM integration tests

### PR DESCRIPTION
**Pull request by vagnerbc**
https://issues.liferay.com/browse/LPS-92858

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by vagnerbc** [comment]
ci:test

**Comment by brandizzi** [comment]
ci:test:relevant

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73265. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
