### PR TITLE
[TECHNICAL-SUPPORT] LPS-70524 Wrong date format in Calendar day view

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @brandizzi 

Long time, no pull request! :smile: 

Could you please check this one, if you are still the reviewer for Calendar-related pulls?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Hey Adam,

I was wondering if you could take a look at this pull.
Please let me know if you have any questions.

Thank you!

Best regards,
István

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hey @IstvanD, indeed it was a long time withouth a pull request ;) @renatorego is taking care of the calendar, so I am forwarding your PR to him. Thank you! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/70. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
