### PR TITLE
LPS-86728 Journal Folder and Journal Article

### PR DESCRIPTION
**Pull request by vagnerbc**
Journal Article with only the tests.

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/leomiyagi/liferay-portal/pull/7. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
