### PR TITLE
LPS-85386 dynamic-data-lists-test: Add integration test to check the indexed fields and reindexing for the DDLRecord and DDLRecordSet.

### PR DESCRIPTION
**Pull request by leomiyagi**

### CODE REVIEW

**Comment by leomiyagi** [comment]
ci:test:search:norebase

**Comment by leomiyagi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/799. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/6c1f74a013f9~6...6c1f74a013f9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
