### PR TITLE
LPS-90067 AssetEntry

### PR DESCRIPTION
**Pull request by vagnerbc**
The AssetEntryIndexer has only the postProcessSearchQuery method.

I deprecated the old AssetEntryIndexer and migrated to a new indexer mode.

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/leomiyagi/liferay-portal/pull/5. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
