### PR TITLE
LSP-85856 New Indexers: mail-reader: Account & Folder & Message

### PR DESCRIPTION
**Pull request by vagnerbc**
You need to deploy all of the email reader modules to run the tests. These modules are not deployed during building.

The folder and the account have only reindexing tests because they do not index any fields during creation.

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/foshiro/liferay-portal/pull/6. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
