### PR TITLE
LPS-75082 Remove the import process restriction when updating the calendar booking.

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52412. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
