### PR TITLE
fixup! fixup! LPS-101102 portal-search-tuning-rankings-web: Display duplicate aliases in error message

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search:norebase <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by joshchong** [comment]
ci:test:bundle

@brandizzi just fyi this PR will require some functional test fixes before sending up. I'll send you a PR once I finish working on them. Thanks!

**Comment by brandizzi** [comment]
Thank you for letting me know, @joshchong! I would probably spend a lot of time concerned about these issues if you didn't say it :swea

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
Hey @thektan @brandizzi, I'm running into an issue with this PR. When trying to create a result ranking, the page will load indefinitely and errors appear in the browser console:
`liferay-amd-loader | A require() call has failed but no failure handler was provided.`

I confirmed that the bug is reproducible with just kevin's latest changes in this PR:
https://github.com/brandizzi/liferay-portal/pull/891

Can you guys look into it? If you want to test it out manually you can download the bundle in this PR here:
https://github.com/brandizzi/liferay-portal/pull/896#issuecomment-562331627
Thanks!

**Comment by thektan** [comment]
@joshchong Ya I can look into it.

**Comment by thektan** [comment]
@joshchong Hmmm...I don't think I'm able to reproduce it. What browser/version are you using?

**Comment by thektan** [comment]
@joshchong Actually it seems as if the bundle created doesn't have the changes applied? I'm still getting the same error page like on upstream. Also I tried deploying Adam's branch and the `liferay-amd-loader` error doesn't appear either. 😕

**Comment by joshchong** [comment]
@thektan hmm, I'm able to see your new validation error message on my bundle when trying to create a duplicate query. Are you sure you're looking started up the right bundle? I was able to reproduce the issue on Chrome 65.0.3325.0, Chrome 78.0.3904.108, Firefox ESR 52.0.2

**Comment by thektan** [comment]
@joshchong I wonder if there's an issue with upstream right now. Running `ci:test:search` on similar result language key changes had a lot of failures for rankings and the screenshots show the portlet not loading. https://github.com/thektan/liferay-portal/pull/102#issuecomment-562368247

**Comment by joshchong** [comment]
Update: we discovered it is a regression that is happening upstream. See https://issues.liferay.com/browse/LPS-105510. Unfortunately, we will have to postpone this PR until that bug is resolved.

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:close

Resent here https://github.com/brandizzi/liferay-portal/pull/899

**Pull request closed without merging**
