### PR TITLE
LPS-59412 Apply new upgrade pattern to calendar

### PR DESCRIPTION
**Pull request by mdelapenya**
cc/ @migue

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
Hello @mdelapenya.

I am not having success on upgrading a database from a 6.2 version (be it the 6.2.x or ee-6.2.x branch, or a released version, EE or CE). The calendar upgrade processes even run  - I could even find a small bug that is already solved - but the resulting portal is unusable.

As I was talking with @migue, I know you all are using some nice dumps to make tests (e.g. the LDN). Would you have one of them so I can proceed with the tests? Of course, it does not need to be the LDN or something that large - only something that would make a good use of the  upgrade processes. Do you have something like that?

Thanks!

**Comment by mdelapenya** [comment]
Hey @brandizzi, you could use this db: https://issues.liferay.com/browse/LPS-59461

Thanks!

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/91. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
