### PR TITLE
Lps 76325 master 2

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi Adam, I apologize for the delay in getting this test case added. Let me know if there are any other questions or issues.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53906. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/529b9c5dc8f9~5...529b9c5dc8f9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53907. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/07a9d7bad1c1~5...07a9d7bad1c1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
