### PR TITLE
LPS-94151 MultiLanguageSearchTest to AssetVocabulary and AssetCategory

### PR DESCRIPTION
**Pull request by vagnerbc**
https://issues.liferay.com/browse/LPS-94135
https://issues.liferay.com/browse/LPS-94151

Created based on CalendarBookingIndexerLocalizedContentTest.

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71799. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
