### PR TITLE
[TECHNICAL-SUPPORT] LPS-76652

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hey @ChrisKian, @jonathanmccann!

Thank you for this fix! We were a bit overwhelmed here and this fix is great.

I just noted that, with this fix, recycled calendars appears in the main portal search. I suspect it is not the expected one! If we are in a hurry, we can merge with that, but then a new ticket would be necessary. Do you think it is feasible to change this behavior? 

Sorry for the delay, I hope it did not cause you guys a lot of issue! (Since LPS-76651 is still open anyway, my wishful thinking says me I did not screwed up too much here :sweat_smile:)

Thanks again! (Also hope you had a great Christmas, and happy new year ;) )

**Comment by ChrisKian** [comment]
Hey @brandizzi,
The deleted calendars should not be searchable from the main search portlet.  I will look into this issue now, thanks!

**Pull request closed without merging**
