### PR TITLE
LPS-85855 Integrate Trash into new indexer model.

### PR DESCRIPTION
**Pull request by luanmaoski**

### CODE REVIEW

**Comment by luanmaoski** [comment]
ci:test:sf

**Comment by luanmaoski** [comment]
ci:test:search

**Comment by luanmaoski** [comment]
ci:test:relevant

**Comment by luanmaoski** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/627. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
