### PR TITLE
LPS-103603 portal-search-tuning-rankings-web: Update icons to lexicon standards

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-99867
https://issues.liferay.com/browse/LPS-99924
https://issues.liferay.com/browse/LPS-99849
https://issues.liferay.com/browse/LPS-103603
https://issues.liferay.com/browse/LPS-99858

Hey @brandizzi, there are 5 tickets with this single PR since they're all related to updating the Result Rankings results display. 

A questionable part I added is logging a warning which I added to avoid the SF error `Unprocessed exception 'PortalException', see LPS-36174` if it's something you're familiar with: https://github.com/brandizzi/liferay-portal/pull/849/commits/30758e9bf9f5b582c3ffc99bbafcd94efdbb5d3c#diff-1180d6727943923c9e22e486290b6f36R132-R138

I also already ran tests on this here https://github.com/thektan/liferay-portal/pull/74 (Failures don't look related)
❌ ci:test:search - 43 out of 46 jobs passed in 1 hour 31 minutes 508 ms 
✔️ ci:test:ci:test:sf - 1 out of 1 jobs passed in 3 minutes 17 seconds 704 ms

Thanks in advance! Let me know if you have any questions!

### CODE REVIEW

**Comment by thektan** [comment]
Sorry to add another ticket to this PR (https://issues.liferay.com/browse/LPS-99858), but they're all related to adjusting the result display. Please let me know if you have any questions.

**Comment by thektan** [comment]
Forced pushed an extra change as part of https://github.com/brandizzi/liferay-portal/pull/849/commits/1091583578483cfda810bb58741a8e1f5baffd06 since it needed a frontend test update.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Most of those fixes are already merged; the last ones are in https://github.com/brianchandotcom/liferay-portal/pull/81023.

**Comment by thektan** [comment]
Thanks for reviewing these @brandizzi! I'll be sure to take a look at any changes you made to keep in mind for future tickets.

**Pull request closed without merging**
