### PR TITLE
LPS-66668 Add poshi test to assign then approve a workflow task as a Portal Content Reviewer

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
POSHI test plan for this issue:

1. Log in as admin (test test)
2. Create a user with Portal Content Reviewer role
3. Select single approver workflow for Blogs
4. Add a blog post
5. Log out, log in as Portal Content Reviewer
6. View notifications
7. Open Blog Post for review
8. Click on ellipsis
9. Click Assign to...
    1. Select Test Test
    2. Save
10. In My Workflow Tasks, assert there are no tasks assigned to you or your roles 
11. View notifications 
12. Assert there are no valid notifications
13. Log out, log in as admin (test test)
14. View notifications
15. Open Blog Post for review
16. Click on ellipsis
17. Click Assign to...
    1. Select the user which role is Portal Content Reviewer
    2. Save
18. In My Workflow Tasks, assert there are no tasks assigned to you or your roles 
19. View notifications
20. Assert you can still open the Blog Post for review 
21. Log out, log in as Portal Content Reviewer
22. View notifications
23. Open Blog Post for review
24. Click on ellipsis
25. Approve Blog Post

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/120. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/fcb135c~1...fcb135c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/487. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/fcb135c~1...fcb135c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/247. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/fcb135c~1...fcb135c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
