### PR TITLE
LPS-75080 Added workflow.email.from.address/name portal properties

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:reopen

**Comment by joshuacords** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52155. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
