### PR TITLE
LPS-85850 New Indexers: BookmarksEntry & BookmarksFolder

### PR DESCRIPTION
**Pull request by ifnazar**

### CODE REVIEW

**Comment by ifnazar** [comment]
@brandizzi : used code of branch brandizzi/pr-585

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67067. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
