### PR TITLE
LPS-70667 Avoid inline edit of day events if the user does not have the right permission

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi @brandizzi,

This pull has come from a technical guidance / discussion in the https://issues.liferay.com/browse/LPP-24464, so please take a look on it, if you need more details, ok? I've discussed with @ricardocousolr about this pull and we both agree it's fine.

If you need anything else, please let me know.

Thanks.

### CODE REVIEW

**Comment by natocesarrego** [comment]
@brandizzi, the issue reported by CI is not related to the changes implemented by this pull.

Regards.

**Comment by brandizzi** [comment]
ci:reopen

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48641. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/f08d9bd~1...f08d9bd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
