### PR TITLE
LPS-73152 UpgradeSchema process was not backported, we need to leave 1.0.* versions for those processes we need to backport

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
@joseMariaMunoz

**Comment by achaparro** [comment]
@brandizzi, could you take a look at this pull? The source formatter since to not be related.

Thanks.

cc @natocesarrego 
cc @JosemariaMunoz

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49975. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49996. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
