### PR TITLE
LPS-92949 portal-search-ranking-web: Synonyms Sets lists

### PR DESCRIPTION
**Pull request by foshiro**
Task: https://issues.liferay.com/browse/LPS-92949

### CODE REVIEW

**Comment by ccohick** [comment]
ci:test:bundle:norebase

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Merged into brandizzi#synonyms <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
