### PR TITLE
LPS-94662 message-boards-test: Create MBThreadMultiLanguageSearchTest

### PR DESCRIPTION
**Pull request by foshiro**
PR reviewed https://github.com/foshiro/liferay-portal/pull/10

### CODE REVIEW

**Comment by foshiro** [comment]
ci:test:sf

**Comment by foshiro** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/793. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
