### PR TITLE
LPS-86736 Create tests for ConfigurationModelIndexer

### PR DESCRIPTION
**Pull request by vagnerbc**
Created only the tests.

The ConfigurationModel class does not implement "BaseModel", the migration does not work, since ModelDocumentContributor and ModelIndexerWriterContributor need a class that implements "BaseModel".

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/leomiyagi/liferay-portal/pull/9. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
