### PR TITLE
LPS-68451 Agenda view in Calendar does not show the events of the month

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alfonsocrisci** [comment]
Hi Adam, Renato,

Thanks so much for working on this issue with István, this is Alfonso and I'm handling the customer's ticket.

Please let us know as soon as there will be an update on this, the customer is eagerly waiting for a final feedback and resolution.

Thanks a lot again !

**Comment by brandizzi** [comment]
cc @marcellustavares @IstvanD @natocesarrego <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43894. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
