### PR TITLE
LPS-70434 Calendar data will not be imported when we are creating user personal pages from a prototype

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey @brandizzi,

This fix is fine for me, but it doesn't have any test associated to it. Can you please implement this test?

Thanks in advance.

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:stop

**Comment by jcampoy** [comment]
Thanks guys! 
@natocesarrego @brandizzi

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
cc @natocesarrego. I guess a test for it will be easy to write once I have this question clarified: https://liferayeng.slack.com/archives/staging-infra-user/p1487955535000007 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47157. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
