### PR TITLE
LPS-95798 portal-search-web: Remove portlet id parameter on search

### PR DESCRIPTION
**Pull request by foshiro**
Task: https://issues.liferay.com/browse/LPS-95798

### CODE REVIEW

**Comment by foshiro** [comment]
ci:test:sf:norebase

**Comment by foshiro** [comment]
ci:test:search:norebase

**Comment by brandizzi** [comment]
ci:test:sf:norebase

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/765. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
