### PR TITLE
LPS-86733 knowledge-base-service: Add tests and multilanguage support for KBArticle.

### PR DESCRIPTION
**Pull request by luanmaoski**

### CODE REVIEW

**Comment by luanmaoski** [comment]
ci:test:search

**Comment by leomiyagi** [comment]
ci:test:sf

**Comment by luanmaoski** [comment]
ci:test:search

**Comment by luanmaoski** [comment]
ci:test:search

**Comment by luanmaoski** [comment]
ci:test:sf

**Comment by luanmaoski** [comment]
ci:test:sf

**Comment by luanmaoski** [comment]
ci:test:search

**Comment by luanmaoski** [comment]
ci:test:sf

**Comment by luanmaoski** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/835. [See changes here.](https://github.com/brandizzi/liferay-portal/compare/8ea8192b6ebf~1...8ea8192b6ebf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
