### PR TITLE
LPS-97798 Add ModelDocumentContributor to ModelSearchDefinition

### PR DESCRIPTION
**Pull request by leomiyagi**

### CODE REVIEW

**Comment by leomiyagi** [comment]
ci:test:search

**Comment by leomiyagi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/817. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
