### PR TITLE
LPS-79338 Journal Folder is missing Multi language search functionality

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/702. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/703. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
