### PR TITLE
LPS-84620 journal-service: Integrate new DDMStructure reindex for JournalArticle

### PR DESCRIPTION
**Pull request by ifnazar**
@brandizzi : the class "DDMStructureIndexerTracker" has been moved to the package "com.liferay.dynamic.data.mapping.internal.search.tracker"

base branch: pr-611

### CODE REVIEW

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:search

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/617. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:test:search <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
