### PR TITLE
[TECHNICAL-SUPPORT] LPS-65333 Calendar Event description disappears

### PR DESCRIPTION
**Pull request by IstvanD**
Hey Adam,

I hope you're doing well.

Could you please review this pull?

It is similar to LPS-58649 in that it set the fields default-locale to the user's language ID.
In LPS-58649 the field was the title, now it is the description.

Thank you!

Greetings,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey Adam,

I was wondering if you could take a look the the pull request.

Thank you!

Best regards,
István

**Comment by brandizzi** [comment]
Hey István!

I'm sorry for the delay. There is a severe bug in the calendar , it is hard dangerous and hard to solve. So, it is taking all my time. 

Yet, I'll try to find some time to review it, at least tomorrow.

Thanks for your patience!

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey Adam,

Thank you for your answer and for starting reviewing the pull.
Fortunately, this bug and it's solution is a whole deal simpler than the complex security issue :)

Nevertheless, I'm looking forward to the results of your review.

Thank you,
István

**Comment by IstvanD** [comment]
Hey Adam,

I'm wondering if you could find time to have a look at the solution.
Because it is an issue reported by a customer, it would be important if we could ship the solution in a timely manner.

Thank you,
István

**Comment by IstvanD** [comment]
Hey Adam,

I'm wondering if you could find time to have a look at the solution.
Because it is an issue reported by a customer, it would be important if we could ship the solution in a timely manner.

Thank you,
István

**Comment by brandizzi** [comment]
Reviewed as https://github.com/marcellustavares/liferay-portal/pull/1403.

**Pull request closed without merging**
