### PR TITLE
LPS-88777 message-boards-test: Update older test to remove content after execution.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:test:relevant

**Comment by brandizzi** [comment]
ci:test

**Comment by brandizzi** [comment]
ci:test:sf

**Comment by joshchong** [comment]
**From ci:test results:**
https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262124/AXIS_VARIABLE=15,label_exp=!master/testReport/

@brandizzi Both the _MBAttachmentsTest_ and _MBMessageIndexerSummaryTest_ tests ran in that group and passed. These changes should be good to push up. The other failures are unrelated.

**Pull request closed without merging**
